trigger:
  batch: true
  branches:
    include:
    - master
    - DEV
    - QA
    - UAT
  paths:
    exclude:
    - azure-pipelines.yml
    - azure-pipelines-TagnRelease.yml
    - azure-pipelines-deploy.yml
    - azure-pipelines-deploy-prod.yml
    - pom.xml

pool:
  vmImage: 'ubuntu-latest'
variables:
- group: Azure-Variable-Group
- name: MAVEN_CACHE_FOLDER
  value: $(Pipeline.Workspace)/.m2/repository
- name: MAVEN_OPTS
  value: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
jobs:
- job: danone_cicd_job
  timeoutInMinutes: 30
  steps:
    - task: CacheBeta@0
      inputs:
        key: $(Build.SourcesDirectory)/hello-world-api//pom.xml
        path: $(MAVEN_CACHE_FOLDER)
      displayName: Cache Maven local repo

    - task: DownloadSecureFile@1
      name: settingsxml
      inputs:
        secureFile: 'settings.xml'

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          New-Item -Type Directory -Force "${HOME}/.m2"
          Copy-Item -Force "$(settingsxml.secureFilePath)" "${HOME}/.m2/settings.xml"
    
    - task: Maven@3
      inputs:
        mavenPomFile: $(Build.SourcesDirectory)/danone-prework-api/pom.xml
        mavenOptions: '-Xmx3072m'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        mavenAuthenticateFeed: true
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        effectivePomSkip: true
        sonarQubeRunAnalysis: false
        goals: 'clean install package deploy $(MAVEN_OPTS)  -DmuleDeploy -Dserver=$(server) -Denvironment=$(environment) -Dworkers=$(workers) -DworkerType=$(workerType) -Dapp.runtime=$(app.runtime) -Dapp.name=$(app.name)'